"rynek": "category"
"zabudowa": "category"
"pietro": "category"
"ogrzewanie": "category"
"stan_wykonczenia": "category"
"forma_wlasnosci": "category"
"teren_zamkniety": "category"
"balkon": "category"
"ogrodek": "category"
"garaz_miejsce": "category"
"winda": "category"
"piwnica": "category"
"monitoring_ochrona": "category"