--------------------------------------------------------
--  File created - piπtek-paüdziernika-02-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table OTODOM_OFFERS_DETAILS
--------------------------------------------------------

  CREATE TABLE "GRZKUP_P"."OTODOM_OFFERS_DETAILS" 
   (	"ID" NUMBER, 
	"ID_OFFERS" NUMBER, 
	"MIASTO" VARCHAR2(100 BYTE), 
	"DZIELNICA" VARCHAR2(100 BYTE), 
	"ULICA" VARCHAR2(100 BYTE), 
	"TYTUL" VARCHAR2(50 BYTE), 
	"POWIERZCHNIA" FLOAT(126), 
	"CENA" NUMBER, 
	"CENA_METR" FLOAT(126), 
	"LICZBA_POKOI" NUMBER, 
	"RYNEK" VARCHAR2(10 BYTE), 
	"ZABUDOWA" VARCHAR2(20 BYTE), 
	"PIETRO" VARCHAR2(10 BYTE), 
	"LICZBA_PIETER" NUMBER, 
	"MATERIAL_BUDYNKU" VARCHAR2(20 BYTE), 
	"OKNA" VARCHAR2(12 BYTE), 
	"OGRZEWANIE" VARCHAR2(20 BYTE), 
	"ROK_BUDOWY" NUMBER, 
	"STAN_WYKONCZENIA" VARCHAR2(20 BYTE), 
	"CZYNSZ" NUMBER, 
	"FORMA_WLASNOSCI" VARCHAR2(30 BYTE), 
	"NUMER_OFERTY" NUMBER, 
	"TEREN_ZAMKNIETY" NUMBER, 
	"BALKON" NUMBER, 
	"OGRODEK" NUMBER, 
	"GARAZ_MIEJSCE" NUMBER, 
	"WINDA" NUMBER, 
	"PIWNICA" NUMBER, 
	"MONITORING_OCHRONA" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRZKUP_P" ;
--------------------------------------------------------
--  DDL for Index OTODOM_OFFERS_DETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "GRZKUP_P"."OTODOM_OFFERS_DETAILS_PK" ON "GRZKUP_P"."OTODOM_OFFERS_DETAILS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRZKUP_P" ;
--------------------------------------------------------
--  DDL for Trigger OTODOM_OFFERS_DETAILS_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "GRZKUP_P"."OTODOM_OFFERS_DETAILS_TRG" 
BEFORE INSERT ON OTODOM_OFFERS_DETAILS 
FOR EACH ROW
BEGIN
  if :NEW.id is null then 
    select OTODOM_OFFERS_DETAILS_SEQ.nextval into :NEW.id from dual; 
  end if; 
END;
/
ALTER TRIGGER "GRZKUP_P"."OTODOM_OFFERS_DETAILS_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table OTODOM_OFFERS_DETAILS
--------------------------------------------------------

  ALTER TABLE "GRZKUP_P"."OTODOM_OFFERS_DETAILS" ADD CONSTRAINT "OTODOM_OFFERS_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "GRZKUP_P"  ENABLE;
 
  ALTER TABLE "GRZKUP_P"."OTODOM_OFFERS_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "GRZKUP_P"."OTODOM_OFFERS_DETAILS" MODIFY ("ID_OFFERS" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table OTODOM_OFFERS_DETAILS
--------------------------------------------------------

  ALTER TABLE "GRZKUP_P"."OTODOM_OFFERS_DETAILS" ADD CONSTRAINT "OTODOM_OFFERS_DETAILS_FK" FOREIGN KEY ("ID_OFFERS")
	  REFERENCES "GRZKUP_P"."OTODOM_OFFERS" ("ID") ENABLE;
